name: Inject modloader and build DolP variants

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  compilation:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip curl jq git

      - name: Get DolP source
        run: |
          git clone --depth 1 https://gitgud.io/Frostberg/degrees-of-lewdity-plus.git degrees-of-lewdity-plus

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: degrees-of-lewdity-plus

      # - name: Build SugarCube v2
      #   run: |
      #     git clone --depth 1 https://github.com/Lyoko-Jeremie/sugarcube-2_Vrelnir sugarcube-2_Vrelnir
      #     cd sugarcube-2_Vrelnir
      #     npm i
      #     node build.js -d -u -b 2
      #     cd ..
      # cp -f sugarcube-2_Vrelnir/dist/format.js degrees-of-lewdity-plus/devTools/tweego/storyFormats/sugarcube-2/

      - name: Download and inject modloader
        run: |
          REPO_OWNER="Lyoko-Jeremie"
          REPO_NAME="sugarcube-2-ModLoader"
          WORKFLOW_NAME="Build-ModLoader-Package.yml"
          ARTIFACT_NAME="ModLoader Package"
          RUN_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_NAME/runs?status=success&per_page=1" \
            | jq -r '.workflow_runs[0].id')
          ARTIFACT_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" \
            | jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .id")
          curl -L -H "Authorization: token $GH_TOKEN" \
            -o modloader.zip \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/artifacts/$ARTIFACT_ID/zip"
          unzip -oq modloader.zip -d ./modloader
          cp ./modloader/dist-insertTools/insert2html.js ./modloader/dist-insertTools/insert2html.cjs
          cp -f ./twine2/sugarcube-2/format.js degrees-of-lewdity-plus/devTools/tweego/storyFormats/sugarcube-2/

      # compiles
      - name: Compile and package modloader
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat ./version)
          mkdir -p DoLP_Modloader/img/
          mkdir -p DoLP_Modloader/mod/

          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_Modloader/
          cp "modList.json" ./DoLP_Modloader/
          cp -r -f ./mod/* ./DoLP_Modloader/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_Modloader/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_Modloader/img/

          ZIP_NAME="../DoLP_Modloader_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_Modloader/

      - name: Compile and package BEEESSS variant
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)
          mkdir -p DoLP_BEEESSS/img/
          mkdir -p DoLP_BEEESSS/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_BEEESSS/
          cp -r -f ./mod/* ./DoLP_BEEESSS/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_BEEESSS/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_BEEESSS/img/
          cp -r -f ./imagepacks/b3s/* ./DoLP_BEEESSS/img/
          cp -r -f ./imagepacks/kaervek/* ./DoLP_BEEESSS/img/
          cp -r -f ./imagepacks/dolp_b3s/* ./DoLP_BEEESSS/img/

          ZIP_NAME="../DoLP_BEEESSS_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_BEEESSS/

      - name: Compile and package BEEESSS Hikari Female
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)
          mkdir -p DoLP_BEEESSS_Hikari_Female/img/
          mkdir -p DoLP_BEEESSS_Hikari_Female/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_BEEESSS_Hikari_Female/
          cp -r -f ./mod/* ./DoLP_BEEESSS_Hikari_Female/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_BEEESSS_Hikari_Female/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_BEEESSS_Hikari_Female/img/
          cp -r -f ./imagepacks/b3s/* ./DoLP_BEEESSS_Hikari_Female/img/
          cp -r -f ./imagepacks/kaervek/* ./DoLP_BEEESSS_Hikari_Female/img/
          cp -r -f ./imagepacks/dolp_b3s/* ./DoLP_BEEESSS_Hikari_Female/img/
          cp -r -f ./imagepacks/b3s_Hikfem/* ./DoLP_BEEESSS_Hikari_Female/img/
          cp -r -f ./imagepacks/b3s_Hikfemsubs/* ./DoLP_BEEESSS_Hikari_Female/img/

          ZIP_NAME="../DoLP_BEEESSS_Hikari_Female_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_BEEESSS_Hikari_Female/

      - name: Compile and package BEEESSS Wax
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)
          mkdir -p DoLP_BEEESSS_Wax/img/
          mkdir -p DoLP_BEEESSS_Wax/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_BEEESSS_Wax/
          cp -r -f ./mod/* ./DoLP_BEEESSS_Wax/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_BEEESSS_Wax/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_BEEESSS_Wax/img/
          cp -r -f ./imagepacks/b3s/* ./DoLP_BEEESSS_Wax/img/
          cp -r -f ./imagepacks/kaervek/* ./DoLP_BEEESSS_Wax/img/
          cp -r -f ./imagepacks/dolp_b3s/* ./DoLP_BEEESSS_Wax/img/
          cp -r -f ./imagepacks/b3s_wax/* ./DoLP_BEEESSS_Wax/img/

          ZIP_NAME="../DoLP_BEEESSS_Wax_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_BEEESSS_Wax/

      - name: Compile and package BEEESSS_mysterious
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)

          mkdir -p DoLP_BEEESSS_mysterious/mod/
          mkdir -p DoLP_BEEESSS_mysterious/img/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_BEEESSS_mysterious/
          cp -r -f ./mod/* ./DoLP_BEEESSS_mysterious/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_BEEESSS_mysterious/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_BEEESSS_mysterious/img/
          cp -r -f ./imagepacks/b3s/* ./DoLP_BEEESSS_mysterious/img/
          cp -r -f ./imagepacks/kaervek/* ./DoLP_BEEESSS_mysterious/img/
          cp -r -f ./imagepacks/dolp_b3s/* ./DoLP_BEEESSS_mysterious/img/
          cp -r -f ./imagepacks/mysterious/* ./DoLP_BEEESSS_mysterious/img/

          ZIP_NAME="../DoLP_BEEESSS_mysterious_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_BEEESSS_mysterious/

      - name: Compile and package Susato
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)

          mkdir -p DoLP_susato/img/
          mkdir -p DoLP_susato/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_susato/
          cp -r -f ./mod/* ./DoLP_susato/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_susato/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_susato/img/
          cp -r -f ./imagepacks/susato/* ./DoLP_susato/img/

          ZIP_NAME="../DoLP_Susato_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_susato/

      - name: Compile and package MIZZ Female
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)

          mkdir -p DoLP_MIZZ_Female/img/
          mkdir -p DoLP_MIZZ_Female/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_MIZZ_Female/
          cp -r -f ./mod/* ./DoLP_MIZZ_Female/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_MIZZ_Female/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_MIZZ_Female/img/
          cp -r -f ./imagepacks/b3s/* ./DoLP_MIZZ_Female/img/
          cp -r -f ./imagepacks/kaervek/* ./DoLP_MIZZ_Female/img/
          cp -r -f ./imagepacks/dolp_b3s/* ./DoLP_MIZZ_Female/img/
          cp -r -f ./imagepacks/mizz/* ./DoLP_MIZZ_Female/img/

          ZIP_NAME="../DoLP_MIZZ_Female_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_MIZZ_Female/

      - name: Compile and package Kitmint
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)

          mkdir -p DoLP_Kitmint/img/
          mkdir -p DoLP_Kitmint/mod/
          cp ./imagepacks/Kitmint/style.css ./
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_Kitmint/
          cp -r -f ./mod/* ./DoLP_MIZZ_Female/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_Kitmint/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_Kitmint/img/
          cp -r -f ./imagepacks/Kitmint/* ./DoLP_Kitmint/img/

          ZIP_NAME="../DoLP_Kitmint_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_Kitmint/

      - name: Compile and package Hikfem_mysterious
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)

          mkdir -p DoLP_Hikfem_mysterious/img/
          mkdir -p DoLP_Hikfem_mysterious/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_Hikfem_mysterious/
          cp -r -f ./mod/* ./DoLP_Hikfem_mysterious/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_Hikfem_mysterious/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_Hikfem_mysterious/img/
          cp -r -f ./imagepacks/b3s/* ./DoLP_Hikfem_mysterious/img/
          cp -r -f ./imagepacks/kaervek/* ./DoLP_Hikfem_mysterious/img/
          cp -r -f ./imagepacks/dolp_b3s/* ./DoLP_Hikfem_mysterious/img/
          cp -r -f ./imagepacks/b3s_Hikfem/* ./DoLP_Hikfem_mysterious/img/
          cp -r -f ./imagepacks/b3s_Hikfemsubs/* ./DoLP_Hikfem_mysterious/img/
          cp -r -f ./imagepacks/mysterious/* ./DoLP_Hikfem_mysterious/img/

          ZIP_NAME="../DoLP_Hikfem_mysterious_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_Hikfem_mysterious/

      - name: Compile and package Goose_female
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)
          mkdir -p DoLP_Goose_female/img/
          mkdir -p DoLP_Goose_female/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_Goose_female/
          cp -r -f ./mod/* ./DoLP_Goose_female/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_Goose_female/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_Goose_female/img/
          cp -r -f ./imagepacks/goosefem/* ./DoLP_Goose_female/img/
          cp -r -f ./imagepacks/goosefemsubs/* ./DoLP_Goose_female/img/

          ZIP_NAME="../DoLP_Goose_female_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_Goose_female/

      - name: Compile and package Goose_female_mysterious
        run: |
          cd degrees-of-lewdity-plus
          VERSION=$(cat version)

          mkdir -p DoLP_Goose_female_mysterious/img/
          mkdir -p DoLP_Goose_female_mysterious/mod/
          bash ./compile.sh
          node "../modloader/dist-insertTools/insert2html.cjs" "./Degrees of Lewdity.html" "../modloader/modList.json" "../modloader/dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_Goose_female_mysterious/
          cp -r -f ./mod/* ./DoLP_Goose_female_mysterious/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_Goose_female_mysterious/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_Goose_female_mysterious/img/
          cp -r -f ./imagepacks/goosefem/* ./DoLP_Goose_female_mysterious/img/
          cp -r -f ./imagepacks/goosefemsubs/* ./DoLP_Goose_female_mysterious/img/
          cp -r -f ./imagepacks/mysterious/* ./DoLP_Goose_female_mysterious/img/

          ZIP_NAME="../DoLP_Goose_female_mysterious_${VERSION}.zip"
          zip -r -q "$ZIP_NAME" ./DoLP_Goose_female_mysterious/

      # create artifacts
      - name: Upload Modloader artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-modloader-package
          path: DoLP_Modloader*.zip

      - name: Upload BEEESSS artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-BEEESSS-package
          path: DoLP_BEEESSS*.zip

      - name: Upload BEEESSS Hikari Female artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-BEEESSS-hikari-female-package
          path: DoLP_BEEESSS_Hikari_Female*.zip

      - name: Upload BEEESSS Wax artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-BEEESSS-wax-package
          path: DoLP_BEEESSS_Wax*.zip

      - name: Upload BEEESSS Mysterious artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-BEEESSS-mysterious-package
          path: DoLP_BEEESSS_mysterious*.zip

      - name: Upload Susato artifact         
        uses: actions/upload-artifact@v4
        with:
          name: dolp-susato-package
          path: DoLP_Susato*.zip
        
      - name: Upload MIZZ Female artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-mizz-female-package
          path: DoLP_MIZZ_Female*.zip

      - name: Upload Kitmint artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-Kitmint-package
          path: DoLP_Kitmint*.zip

      - name: Upload Hikfem Mysterious artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-Hikfem-mysterious-package
          path: DoLP_Hikfem_mysterious*.zip

      - name: Upload Goose Female artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-goose-female-package
          path: DoLP_Goose_female*.zip

      - name: Upload Goose Female Mysterious artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolp-goose-female-mysterious-package
          path: DoLP_Goose_female_mysterious*.zip

  create-release:
    runs-on: ubuntu-latest
    needs: compilation
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: manual-release-${{ github.run_number }}
          name: DoLP Release ${{ github.run_number }}
          body: |
            Auto-release for commit ${{ github.sha }}
            Includes:
            - Modloader
            - BEEESSS
            - BEEESSS Hikari Female
            - BEEESSS Wax
            - Susato
            - MIZZ Female
            - Kitmint
            - BEEESSS_mysterious
            - Hikfem_mysterious
            - Goose_female
            - Goose_female_mysterious
          files: |
            DoLP_Modloader_*.zip
            DoLP_BEEESSS_*.zip
            DoLP_BEEESSS_*.zip
            DoLP_BEEESSS_Wax_*.zip
            DoLP_Susato_*.zip
            DoLP_MIZZ_Female_*.zip
            DoLP_Kitmint_*.zip
            DoLP_BEEESSS_mysterious_*.zip
            DoLP_Hikfem_mysterious_*.zip
            DoLP_Goose_female_*.zip
            DoLP_Goose_female_mysterious_*.zip

      - name: Cleanup
        run: |
          rm -rf DoLP_*_v0.*
