name: Inject modloader and build DolP variants

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  compilation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip curl jq git

      - name: Get DolP source
        run: |
          git clone --depth 1 https://gitgud.io/Frostberg/degrees-of-lewdity-plus/ temp-src

      - name: Generate version
        id: set-version
        run: |
          VERSION="v0.${{ github.run_id }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      - name: Download insertTools artifact
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          REPO_OWNER="Lyoko-Jeremie"
          REPO_NAME="sugarcube-2-ModLoader"
          WORKFLOW_NAME="Build-ModLoader-Package.yml"
          ARTIFACT_NAME="insertTools"

          RUN_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_NAME/runs?status=success&per_page=1" \
            | jq -r '.workflow_runs[0].id')

          ARTIFACT_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID/artifacts" \
            | jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .id")

          curl -L -H "Authorization: token $GH_TOKEN" \
            -o insertTools.zip \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/artifacts/$ARTIFACT_ID/zip"

          unzip -o insertTools.zip -d temp-src/dist-insertTools/

      - name: Replace version strings
        run: |
          VERSION="${{ steps.set-version.outputs.version }}"
          find ./temp-src/version -type f -exec sed -i "s/DoLP version/DoLP $VERSION/g" {} +
          find ./temp-src/devTools/androidsdk/image/cordova/config.xml -type f -exec sed -i "s/DoLP version/DoLP $VERSION/g" {} +
          find ./temp-src/devTools/apkbuilder/config.xml -type f -exec sed -i "s/DoLP version/DoLP $VERSION/g" {} +
          find ./temp-src/game/01-config/sugarcubeConfig.js -type f -exec sed -i "s/DoLP version/DoLP $VERSION/g" {} +

      - name: Compile and package modloader
        run: |
          VERSION="${{ steps.set-version.outputs.version }}"
          cd temp-src
          mkdir -p DoLP_Modloader/img/
          mkdir -p DoLP_Modloader/mod/

          sh ./compile.sh
          node "dist-insertTools/insert2html.cjs" "Degrees of Lewdity.html" "modList.json" "dist-BeforeSC2/BeforeSC2.js"

          cp "Degrees of Lewdity.html.mod.html" ./DoLP_Modloader/
          cp "modList.json" ./DoLP_Modloader/
          cp -r -f ./mod/* ./DoLP_Modloader/mod/
          cp -r -f ./imagepacks/vanilla/* ./DoLP_Modloader/img/
          cp -r -f ./imagepacks/dolp/* ./DoLP_Modloader/img/

          zip -r ../DoLP_Modloader_${VERSION}.zip ./DoLP_Modloader/

      - name: Upload artifact for next job
        uses: actions/upload-artifact@v4
        with:
          name: dolp-modloader-package
          path: DoLP_Modloader_*.zip

  upload:
    runs-on: ubuntu-latest
    needs: compilation
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dolp-modloader-package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.compilation.outputs.version }}
          name: DoLP Modloader Release ${{ needs.compilation.outputs.version }}
          files: DoLP_Modloader_*.zip
          body: "Auto-release for commit ${{ github.sha }}"

      - name: Cleanup
        run: |
          rm -rf DoLP_Modloader*
          echo "Finished creating releases."
